-- CreateTable
CREATE TABLE "TC_COMM_CD_GRP" (
    "id" SERIAL NOT NULL,
    "CD_GRP_ID" TEXT NOT NULL,
    "CD_GRP_NM" TEXT NOT NULL,
    "CD_GRP_DC" TEXT,
    "USE_YN" TEXT NOT NULL DEFAULT 'Y',
    "RGST_DT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "RGTR_ID" TEXT,
    "MDFCN_DT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "MDFR_ID" TEXT,
    "DEL_YN" TEXT NOT NULL DEFAULT 'N',

    CONSTRAINT "TC_COMM_CD_GRP_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TC_COMM_CD" (
    "id" SERIAL NOT NULL,
    "CD_GRP_ID" TEXT NOT NULL,
    "CD_VAL" TEXT NOT NULL,
    "CD_NM" TEXT NOT NULL,
    "CD_DC" TEXT,
    "SORT_NO" INTEGER NOT NULL,
    "USE_YN" TEXT NOT NULL DEFAULT 'Y',
    "RGST_DT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "RGTR_ID" TEXT,
    "MDFCN_DT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "MDFR_ID" TEXT,
    "DEL_YN" TEXT NOT NULL DEFAULT 'N',

    CONSTRAINT "TC_COMM_CD_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TB_COMM_USER" (
    "id" SERIAL NOT NULL,
    "USE_EML" TEXT NOT NULL,
    "FIREBASE_UID" TEXT NOT NULL,
    "USE_NM" TEXT NOT NULL,
    "USE_NCNM" TEXT,
    "PRFL_IMG_URL" TEXT,
    "USE_ROLE_CD" TEXT NOT NULL DEFAULT 'BUYER',
    "USE_STTS_CD" TEXT NOT NULL DEFAULT 'ACTV',
    "LST_LGN_DT" TIMESTAMP(3),
    "RGST_DT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "RGTR_ID" TEXT,
    "MDFCN_DT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "MDFR_ID" TEXT,
    "DEL_YN" TEXT NOT NULL DEFAULT 'N',

    CONSTRAINT "TB_COMM_USER_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TL_COMM_LGN_LOG" (
    "id" SERIAL NOT NULL,
    "USE_ID" INTEGER NOT NULL,
    "LGN_MTHD_CD" TEXT NOT NULL,
    "LGN_DT" TIMESTAMP(3) NOT NULL,
    "LGN_IP_ADDR" TEXT NOT NULL,
    "LGN_RSLT_CD" TEXT NOT NULL,
    "FAIL_RSN" TEXT,
    "USE_AGNT" TEXT,
    "RGST_DT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "RGTR_ID" TEXT,

    CONSTRAINT "TL_COMM_LGN_LOG_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TL_COMM_EML_LOG" (
    "id" SERIAL NOT NULL,
    "RCPNT_EML" TEXT NOT NULL,
    "SBJ" TEXT NOT NULL,
    "TMPLT_NM" TEXT NOT NULL,
    "SND_STTS_CD" TEXT NOT NULL,
    "ERR_MSG" TEXT,
    "SND_DT" TIMESTAMP(3) NOT NULL,
    "MTDT" JSONB,
    "RGST_DT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TL_COMM_EML_LOG_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TB_COMM_BOARD_POST" (
    "id" SERIAL NOT NULL,
    "USE_ID" INTEGER NOT NULL,
    "POST_TTL" TEXT NOT NULL,
    "POST_CN" TEXT NOT NULL,
    "POST_CTGR_CD" TEXT NOT NULL,
    "INQR_CNT" INTEGER NOT NULL DEFAULT 0,
    "LIKE_CNT" INTEGER NOT NULL DEFAULT 0,
    "CMNT_CNT" INTEGER NOT NULL DEFAULT 0,
    "PNND_YN" TEXT NOT NULL DEFAULT 'N',
    "SRCH_TAGS" TEXT[],
    "RGST_DT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "RGTR_ID" TEXT,
    "MDFCN_DT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "MDFR_ID" TEXT,
    "DEL_YN" TEXT NOT NULL DEFAULT 'N',

    CONSTRAINT "TB_COMM_BOARD_POST_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TB_COMM_BOARD_CMNT" (
    "id" SERIAL NOT NULL,
    "POST_ID" INTEGER NOT NULL,
    "USE_ID" INTEGER NOT NULL,
    "CMNT_CN" TEXT NOT NULL,
    "PRNT_CMNT_ID" INTEGER,
    "CMNT_DPTH" INTEGER NOT NULL,
    "RGST_DT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "RGTR_ID" TEXT,
    "MDFCN_DT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "MDFR_ID" TEXT,
    "DEL_YN" TEXT NOT NULL DEFAULT 'N',

    CONSTRAINT "TB_COMM_BOARD_CMNT_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TB_COMM_BOARD_ATCH" (
    "id" SERIAL NOT NULL,
    "POST_ID" INTEGER NOT NULL,
    "ATCH_TYPE_CD" TEXT NOT NULL,
    "ATCM_NM" TEXT NOT NULL,
    "ATCM_URL" TEXT NOT NULL,
    "ATCM_SIZE" INTEGER NOT NULL,
    "ATCM_MIME_TYPE" TEXT NOT NULL,
    "SORT_NO" INTEGER NOT NULL,
    "RGST_DT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "RGTR_ID" TEXT,
    "MDFCN_DT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "MDFR_ID" TEXT,
    "DEL_YN" TEXT NOT NULL DEFAULT 'N',

    CONSTRAINT "TB_COMM_BOARD_ATCH_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TB_COMM_BOARD_BANNER" (
    "id" SERIAL NOT NULL,
    "IMG_URL" TEXT NOT NULL,
    "TTL" TEXT,
    "SUB_TTL" TEXT,
    "LNK_URL" TEXT,
    "USE_YN" TEXT NOT NULL DEFAULT 'Y',
    "RGTR_ID" TEXT NOT NULL,
    "MDFR_ID" TEXT NOT NULL,
    "RGST_DT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "MDFCN_DT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TB_COMM_BOARD_BANNER_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TR_COMM_BOARD_LIKE" (
    "id" SERIAL NOT NULL,
    "POST_ID" INTEGER NOT NULL,
    "USE_ID" INTEGER NOT NULL,
    "RGST_DT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TR_COMM_BOARD_LIKE_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TB_PROD_PRD" (
    "id" SERIAL NOT NULL,
    "SLLR_ID" INTEGER NOT NULL,
    "PRD_NM" TEXT NOT NULL,
    "PRD_DC" TEXT NOT NULL,
    "PRD_PRC" DOUBLE PRECISION NOT NULL,
    "PRD_SALE_PRC" DOUBLE PRECISION,
    "PRD_CTGR_CD" TEXT NOT NULL,
    "PRD_STTS_CD" TEXT NOT NULL DEFAULT 'ACTV',
    "PRD_IMG_URL" TEXT NOT NULL,
    "PRD_IMG_URLS" TEXT[],
    "STCK_QTY" INTEGER NOT NULL DEFAULT 0,
    "SOLD_CNT" INTEGER NOT NULL DEFAULT 0,
    "VIEW_CNT" INTEGER NOT NULL DEFAULT 0,
    "AVG_RTNG" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "RVW_CNT" INTEGER NOT NULL DEFAULT 0,
    "SRCH_TAGS" TEXT[],
    "RGST_DT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "RGTR_ID" TEXT,
    "MDFCN_DT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "MDFR_ID" TEXT,
    "DEL_YN" TEXT NOT NULL DEFAULT 'N',

    CONSTRAINT "TB_PROD_PRD_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TB_COMM_CHAT_ROOM" (
    "id" SERIAL NOT NULL,
    "CHAT_ROOM_NM" TEXT NOT NULL,
    "CHAT_ROOM_TYPE_CD" TEXT NOT NULL,
    "MAX_MBR_CNT" INTEGER NOT NULL,
    "CRTR_ID" INTEGER NOT NULL,
    "LST_MSSG_CN" TEXT,
    "LST_MSSG_DT" TIMESTAMP(3),
    "RGST_DT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "RGTR_ID" TEXT,
    "MDFCN_DT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "MDFR_ID" TEXT,
    "DEL_YN" TEXT NOT NULL DEFAULT 'N',

    CONSTRAINT "TB_COMM_CHAT_ROOM_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TR_COMM_CHAT_ROOM_MBR" (
    "id" SERIAL NOT NULL,
    "CHAT_ROOM_ID" INTEGER NOT NULL,
    "USE_ID" INTEGER NOT NULL,
    "JOIN_DT" TIMESTAMP(3) NOT NULL,
    "LAST_READ_DT" TIMESTAMP(3),
    "NOTI_YN" TEXT NOT NULL DEFAULT 'Y',

    CONSTRAINT "TR_COMM_CHAT_ROOM_MBR_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TB_COMM_CHAT_MSG" (
    "id" SERIAL NOT NULL,
    "CHAT_ROOM_ID" INTEGER NOT NULL,
    "USE_ID" INTEGER NOT NULL,
    "MSSG_CN" TEXT NOT NULL,
    "MSSG_TYPE_CD" TEXT NOT NULL,
    "SEND_DT" TIMESTAMP(3) NOT NULL,
    "RGST_DT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "RGTR_ID" TEXT,

    CONSTRAINT "TB_COMM_CHAT_MSG_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TB_COMM_CHAT_MSG_ATCH" (
    "id" SERIAL NOT NULL,
    "MSSG_ID" INTEGER NOT NULL,
    "ATCM_NM" TEXT NOT NULL,
    "ATCM_URL" TEXT NOT NULL,
    "ATCM_SIZE" INTEGER NOT NULL,
    "ATCM_MIME_TYPE" TEXT NOT NULL,
    "THMB_URL" TEXT,
    "RGST_DT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "RGTR_ID" TEXT,

    CONSTRAINT "TB_COMM_CHAT_MSG_ATCH_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TB_COMM_ORDR" (
    "id" SERIAL NOT NULL,
    "ORDR_NO" TEXT NOT NULL,
    "BYR_ID" INTEGER NOT NULL,
    "ORDR_TOT_AMT" DOUBLE PRECISION NOT NULL,
    "ORDR_STTS_CD" TEXT NOT NULL DEFAULT 'PENDING',
    "SHIP_ADDR" TEXT,
    "SHIP_RCVR_NM" TEXT,
    "SHIP_TELNO" TEXT,
    "SHIP_MEMO" TEXT,
    "TRCKG_NO" TEXT,
    "PAY_MTHD_CD" TEXT,
    "RGST_DT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "RGTR_ID" TEXT,
    "MDFCN_DT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "MDFR_ID" TEXT,
    "DEL_YN" TEXT NOT NULL DEFAULT 'N',

    CONSTRAINT "TB_COMM_ORDR_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TB_COMM_ORDR_ITEM" (
    "id" SERIAL NOT NULL,
    "ORDR_ID" INTEGER NOT NULL,
    "PRD_ID" INTEGER NOT NULL,
    "SLLR_ID" INTEGER NOT NULL,
    "PRD_NM" TEXT NOT NULL,
    "PRD_IMG_URL" TEXT NOT NULL,
    "UNIT_PRC" DOUBLE PRECISION NOT NULL,
    "ORDR_QTY" INTEGER NOT NULL,
    "SUBTOT_AMT" DOUBLE PRECISION NOT NULL,
    "ITEM_STTS_CD" TEXT NOT NULL DEFAULT 'PENDING',
    "PAY_STTS" TEXT NOT NULL DEFAULT 'UNPAID',
    "TRCKG_NO" TEXT,
    "RGST_DT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "RGTR_ID" TEXT,
    "MDFCN_DT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "MDFR_ID" TEXT,
    "DEL_YN" TEXT NOT NULL DEFAULT 'N',

    CONSTRAINT "TB_COMM_ORDR_ITEM_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TH_COMM_ORDR_STTS" (
    "id" SERIAL NOT NULL,
    "ORDR_ID" INTEGER NOT NULL,
    "PREV_STTS_CD" TEXT NOT NULL,
    "NEW_STTS_CD" TEXT NOT NULL,
    "CHNG_RSN" TEXT,
    "CHNGR_ID" INTEGER NOT NULL,
    "CHNG_DT" TIMESTAMP(3) NOT NULL,
    "RGST_DT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "RGTR_ID" TEXT,

    CONSTRAINT "TH_COMM_ORDR_STTS_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TL_COMM_USE_ACTV" (
    "id" SERIAL NOT NULL,
    "USE_ID" INTEGER NOT NULL,
    "ACTV_TYPE_CD" TEXT NOT NULL,
    "PREV_VAL" TEXT,
    "NEW_VAL" TEXT,
    "PRFMR_ID" INTEGER NOT NULL,
    "CLNT_IP_ADDR" TEXT,
    "ACTV_DT" TIMESTAMP(3) NOT NULL,
    "RGST_DT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "RGTR_ID" TEXT,

    CONSTRAINT "TL_COMM_USE_ACTV_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "TC_COMM_CD_GRP_CD_GRP_ID_key" ON "TC_COMM_CD_GRP"("CD_GRP_ID");

-- CreateIndex
CREATE UNIQUE INDEX "TC_COMM_CD_CD_GRP_ID_CD_VAL_key" ON "TC_COMM_CD"("CD_GRP_ID", "CD_VAL");

-- CreateIndex
CREATE UNIQUE INDEX "TB_COMM_USER_USE_EML_key" ON "TB_COMM_USER"("USE_EML");

-- CreateIndex
CREATE UNIQUE INDEX "TB_COMM_USER_FIREBASE_UID_key" ON "TB_COMM_USER"("FIREBASE_UID");

-- CreateIndex
CREATE UNIQUE INDEX "TB_COMM_USER_USE_NCNM_key" ON "TB_COMM_USER"("USE_NCNM");

-- CreateIndex
CREATE UNIQUE INDEX "TR_COMM_BOARD_LIKE_POST_ID_USE_ID_key" ON "TR_COMM_BOARD_LIKE"("POST_ID", "USE_ID");

-- CreateIndex
CREATE UNIQUE INDEX "TR_COMM_CHAT_ROOM_MBR_CHAT_ROOM_ID_USE_ID_key" ON "TR_COMM_CHAT_ROOM_MBR"("CHAT_ROOM_ID", "USE_ID");

-- CreateIndex
CREATE UNIQUE INDEX "TB_COMM_ORDR_ORDR_NO_key" ON "TB_COMM_ORDR"("ORDR_NO");

-- AddForeignKey
ALTER TABLE "TC_COMM_CD" ADD CONSTRAINT "TC_COMM_CD_CD_GRP_ID_fkey" FOREIGN KEY ("CD_GRP_ID") REFERENCES "TC_COMM_CD_GRP"("CD_GRP_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TL_COMM_LGN_LOG" ADD CONSTRAINT "TL_COMM_LGN_LOG_USE_ID_fkey" FOREIGN KEY ("USE_ID") REFERENCES "TB_COMM_USER"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TB_COMM_BOARD_POST" ADD CONSTRAINT "TB_COMM_BOARD_POST_USE_ID_fkey" FOREIGN KEY ("USE_ID") REFERENCES "TB_COMM_USER"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TB_COMM_BOARD_CMNT" ADD CONSTRAINT "TB_COMM_BOARD_CMNT_USE_ID_fkey" FOREIGN KEY ("USE_ID") REFERENCES "TB_COMM_USER"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TB_COMM_BOARD_CMNT" ADD CONSTRAINT "TB_COMM_BOARD_CMNT_POST_ID_fkey" FOREIGN KEY ("POST_ID") REFERENCES "TB_COMM_BOARD_POST"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TB_COMM_BOARD_ATCH" ADD CONSTRAINT "TB_COMM_BOARD_ATCH_POST_ID_fkey" FOREIGN KEY ("POST_ID") REFERENCES "TB_COMM_BOARD_POST"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TR_COMM_BOARD_LIKE" ADD CONSTRAINT "TR_COMM_BOARD_LIKE_POST_ID_fkey" FOREIGN KEY ("POST_ID") REFERENCES "TB_COMM_BOARD_POST"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TR_COMM_BOARD_LIKE" ADD CONSTRAINT "TR_COMM_BOARD_LIKE_USE_ID_fkey" FOREIGN KEY ("USE_ID") REFERENCES "TB_COMM_USER"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TB_PROD_PRD" ADD CONSTRAINT "TB_PROD_PRD_SLLR_ID_fkey" FOREIGN KEY ("SLLR_ID") REFERENCES "TB_COMM_USER"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TB_COMM_CHAT_ROOM" ADD CONSTRAINT "TB_COMM_CHAT_ROOM_CRTR_ID_fkey" FOREIGN KEY ("CRTR_ID") REFERENCES "TB_COMM_USER"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TR_COMM_CHAT_ROOM_MBR" ADD CONSTRAINT "TR_COMM_CHAT_ROOM_MBR_CHAT_ROOM_ID_fkey" FOREIGN KEY ("CHAT_ROOM_ID") REFERENCES "TB_COMM_CHAT_ROOM"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TR_COMM_CHAT_ROOM_MBR" ADD CONSTRAINT "TR_COMM_CHAT_ROOM_MBR_USE_ID_fkey" FOREIGN KEY ("USE_ID") REFERENCES "TB_COMM_USER"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TB_COMM_CHAT_MSG" ADD CONSTRAINT "TB_COMM_CHAT_MSG_CHAT_ROOM_ID_fkey" FOREIGN KEY ("CHAT_ROOM_ID") REFERENCES "TB_COMM_CHAT_ROOM"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TB_COMM_CHAT_MSG" ADD CONSTRAINT "TB_COMM_CHAT_MSG_USE_ID_fkey" FOREIGN KEY ("USE_ID") REFERENCES "TB_COMM_USER"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TB_COMM_CHAT_MSG_ATCH" ADD CONSTRAINT "TB_COMM_CHAT_MSG_ATCH_MSSG_ID_fkey" FOREIGN KEY ("MSSG_ID") REFERENCES "TB_COMM_CHAT_MSG"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TB_COMM_ORDR" ADD CONSTRAINT "TB_COMM_ORDR_BYR_ID_fkey" FOREIGN KEY ("BYR_ID") REFERENCES "TB_COMM_USER"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TB_COMM_ORDR_ITEM" ADD CONSTRAINT "TB_COMM_ORDR_ITEM_ORDR_ID_fkey" FOREIGN KEY ("ORDR_ID") REFERENCES "TB_COMM_ORDR"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TB_COMM_ORDR_ITEM" ADD CONSTRAINT "TB_COMM_ORDR_ITEM_PRD_ID_fkey" FOREIGN KEY ("PRD_ID") REFERENCES "TB_PROD_PRD"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TB_COMM_ORDR_ITEM" ADD CONSTRAINT "TB_COMM_ORDR_ITEM_SLLR_ID_fkey" FOREIGN KEY ("SLLR_ID") REFERENCES "TB_COMM_USER"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TH_COMM_ORDR_STTS" ADD CONSTRAINT "TH_COMM_ORDR_STTS_ORDR_ID_fkey" FOREIGN KEY ("ORDR_ID") REFERENCES "TB_COMM_ORDR"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TH_COMM_ORDR_STTS" ADD CONSTRAINT "TH_COMM_ORDR_STTS_CHNGR_ID_fkey" FOREIGN KEY ("CHNGR_ID") REFERENCES "TB_COMM_USER"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TL_COMM_USE_ACTV" ADD CONSTRAINT "TL_COMM_USE_ACTV_USE_ID_fkey" FOREIGN KEY ("USE_ID") REFERENCES "TB_COMM_USER"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TL_COMM_USE_ACTV" ADD CONSTRAINT "TL_COMM_USE_ACTV_PRFMR_ID_fkey" FOREIGN KEY ("PRFMR_ID") REFERENCES "TB_COMM_USER"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
